{{- if and .Values.slack.createSecret .Values.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.slack.existingSecret }}
  labels:
    {{- include "cloud-service-status-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.slack.secretKey }}: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
